name: cnn-cancer-classifier
channels:
  - defaults
  - conda-forge
  - anaconda

dependencies:
  - python=3.9
  - tensorflow=2.12.0
  - pandas
  - gdown
  - dvc
  - mlflow=2.2.2
  - notebook
  - numpy
  - matplotlib
  - seaborn
  - python-box=6.0.2
  - python-dotenv
  - pyyaml
  - tqdm
  - ensure=1.0.2
  - joblib
  - types-pyyaml
  - scipy
  - scikit-learn
  - fastapi
  - uvicorn
  - pip
  - pip:
      - -e .
